# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 17:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_auto_20190519_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
